name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: Add target
      run: rustup target add aarch64-apple-darwin
    
    - name: Build X86_64
      run: cargo build --verbose
    
    - name: Build AARCH64
      run: cargo build --verbose --target aarch64-apple-darwin
