name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3    

    - name: Build QT (AARCH64)
      run: |
        mkdir qt-aarch64
        cd qt-aarch64
        wget -q https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
        tar -xf qt-everywhere-src-5.15.2.tar.xz
        cd qt-everywhere-src-5.15.2
        ./configure -opensource -nomake examples -nomake tests -platform macx-clang QMAKE_APPLE_DEVICE_ARCHS=arm64 -prefix /usr/local/QT-5.15.2-arm
        make
        make install        

    - name: Install Qt (X86_64)
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
    
    - name: Add target
      run: rustup add target aarch64-apple-darwin
    
    - name: Build X86_64
      run: cargo build --verbose
    
    - name: Build AARCH64
      run: cargo build --verbose --target aarch64-apple-darwin
      
    
